export const dataProjetos =[
    {
        id=0,
        nome='Missão Tikuna',
        tipo='Site para ONG',
        ano='2018-2021',
        images: require('./imagens/Banner_Site_MissaoTikuna.PNG').default,
        url: 'https://missaotikuna.org/',
        status: 'on-line',
    },
    {
        id=1,
        nome='Curso Tikuna',
        tipo='Site para ONG',
        ano='2018-2021',
        images: require('./imagens/Banner_Site_MissaoTikuna.PNG').default,
        url: 'https://missaotikuna.org/',
        status: 'off-line',
    },
    {
        id=2,
        nome='Missão Tikuna',
        tipo='Site para ONG',
        ano='2000-2021',
        images: require('./imagens/Banner_Site_MissaoTikuna.PNG').default,
        url: 'https://missaotikuna.org/',
        status: 'on-line',
    },
    {
        id=3,
        nome='Missão Tikuna',
        tipo='Site para ONG',
        ano='2019-2021',
        images: require('./imagens/Banner_Site_MissaoTikuna.PNG').default,
        url: 'https://missaotikuna.org/',
        status: 'on-line',
    },
    {
        id=4,
        nome='Missão Tikuna',
        tipo='Site para ONG',
        ano='2018',
        images: require('./imagens/Banner_Site_MissaoTikuna.PNG').default,
        url: 'https://missaotikuna.org/',
        status: 'on-line',
    },
];