export const dataProjetos =[
    {
        id: 1,
        nome:'Missão Tikuna',
        tipo:'Site para ONG',
        ano:'2018-2021',
        images: require('./imagens/Book_MissaoTikuna.jpg').default,
        url: 'https://missaotikuna.org/',
        status: 'on-line',
    },
    {
        id: 2,
        nome:'SEEDUC',
        tipo:'Suporte em TI',
        ano:'2021',
        images: require('./imagens/Book_SuporteTI.jpg').default,
        url: 'https://missaotikuna.org/',
        status: 'off-line',
    },
    {
        id: 3,
        nome:'Curso Domínio Público',
        tipo:'Edição de Videos',
        ano:'2018',
        images: require('./imagens/Book_CursoDominioPublico.jpg').default,
        url: 'https://www.cursodominiopublico.com.br/',
        status: 'on-line',
    },
    {
        id: 4,
        nome:'Missão Tikuna',
        tipo:'Site para ONG',
        ano:'2019-2021',
        images: require('./imagens/Banner_Site_MissaoTikuna.PNG').default,
        url: 'https://missaotikuna.org/',
        status: 'on-line',
    },
    {
        id: 5,
        nome:'Missão Tikuna',
        tipo:'Site para ONG',
        ano:'2018',
        images: require('./imagens/Banner_Site_MissaoTikuna.PNG').default,
        url: 'https://missaotikuna.org/',
        status: 'on-line',
    },
    {
        id: 6,
        nome:'Missão Tikuna',
        tipo:'Site para ONG',
        ano:'2018',
        images: require('./imagens/Banner_Site_MissaoTikuna.PNG').default,
        url: 'https://missaotikuna.org/',
        status: 'on-line',
    },
];